sqlite3_test:
  adapter: sqlite3
  database: ":memory:"
  timeout: 500

postgresql_test:
  adapter: postgresql
  database: order_as_specified_test
  username: postgres

mysql_test:
  adapter: mysql2
  database: order_as_specified_test
  username: travis
  encoding: utf8
